FROM centos:centos7

# Perform the installation as root:
USER root
ENV HOME /home/ilc
ENV ILCSOFT /home/ilc/ilcsoft


WORKDIR ${HOME}


RUN yum -y update \
    && yum install -y \
                curl \ 
                tar \
                bzip2 \
                wget \
                tar \
                git \
                which \
                make \
                libX11-devel \
                libXext-devel \
                freeglut-devel \
                libXmu-devel \
                libXpm-devel \
                libXft-devel \
                python-devel \ 
                boost-devel \
                subversion \
                doxygen \
                texlive \
                mysql \
                mysql-devel && \
        yum clean all


RUN  yum install -y centos-release-scl  
RUN  yum install -y devtoolset-8-gcc-c++ 

SHELL [ "/usr/bin/scl", "enable", "devtoolset-8"]


## install the base 
RUN git clone https://github.com/rete/iLCInstall.git --branch fix-root-cmake 
WORKDIR ${HOME}/iLCInstall
RUN ./ilcsoft-install -i --install-prefix ${ILCSOFT} -j 30 releases/HEAD/release-base.cfg

## Installing Eigen3 
RUN wget http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/e/eigen3-devel-3.3.4-6.el7.noarch.rpm && \
    rpm -Uvh eigen3-devel-3.3.4-6.el7.noarch.rpm 

## Delete unnecessary build folders
RUN rm -rf /home/ilc/ilcsoft/geant4/build-* && \
    rm -rf /home/ilc/ilcsoft/root/build-* && \
    rm -rf /home/ilc/ilcsoft/Qt5/v5.13.1/build

RUN mkdir -p ${ILCSOFT} && \
    ./ilcsoft-install -i --install-prefix ${ILCSOFT} releases/HEAD/release-ilcsoft.cfg

# Start the image with BASH by default
CMD ["/bin/bash"]
